### PR TITLE
Feat/bac 53: added delete endpoints for currency and rate objects

### PR DESCRIPTION
**Pull request by jpphilips**
[BAC-53](https://linear.app/team-bevel/issue/BAC-53/build-delete-endpoints-for-currency-and-rate-objects)

Delete Currency Endpoint
- Takes the iso code of a country
- calls the delete_currency_by_isocode function in crud/currency.py
-  deletes currency and all associated rates if the query is successful 
- returns response

Delete Currency Endpoint
- Takes the rate id
- calls the remove function in crud/base.py
-  deletes rate if the query is successful 
- returns response

Additions
- removed redundant conditions in delete_currency_by_isocode function
- moved add_rate endpoint to admin 
- added nullable argument to currency_id in models/rate to prevent rates being added without a relationship to the countries table
- added currency_id to rate schema to fix add_rate endpoint
- resolved conflicts with feature branch and dev

### CODE REVIEW

**Review by AmbroseOtundo — COMMENTED** [review]
Please solve this issue i am getting while running your endpoint. Check the error in this screen shot
Capture

**Comment by jpphilips** [comment]
Which of the endpoints?

**Comment by jpphilips** [comment]
Yes

**Comment by AmbroseOtundo** [comment]
I deleted the db and run the server and it works now correctly.

**Review by AmbroseOtundo — APPROVED** [review]

**Comment by jpphilips** [comment]
There's a new constraint in the db for data integrity. 
Previously you could add a rate without a relationship to the countries table. Not anymore, but requires you to recreate the tables.
This might be why deleting the db and running again was necessary.

**Comment by AmbroseOtundo** [comment]
Alright, I was trying to pull and there was an issue with the db. Now I am in the know .

**Review by EngrZaks — APPROVED** [review]

**Comment by jpphilips** [comment]
The correct api endpoint tags were used in [this pr](https://github.com/workshopapps/realxchangerate.web/pull/177)

**Pull request merged**
